# Tests (sorted by expected completion time)
TESTPROGRAMS =			\
	region-test		\
	region-translate-test	\
	region-contains-test	\
	$(NULL)

# Utility functions
libutils_sources =		\
	utils.c			\
	utils-prng.c		\
	$(NULL)

libutils_headers =		\
	utils.h			\
	utils-prng.h		\
	$(NULL)
